// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHvTWY2pGk5oWLuzvrgrpMM9gFTNLXTA',
    appId: '1:324367349082:web:51cb3a225c56ec7b26ef63',
    messagingSenderId: '324367349082',
    projectId: 'crud-c8dd3',
    authDomain: 'crud-c8dd3.firebaseapp.com',
    storageBucket: 'crud-c8dd3.firebasestorage.app',
    measurementId: 'G-1C1SKQLSTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzkBYdcPh7LBLITvNza7EUgbuTWo7iBY',
    appId: '1:324367349082:android:ac69e9b1536b081726ef63',
    messagingSenderId: '324367349082',
    projectId: 'crud-c8dd3',
    storageBucket: 'crud-c8dd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0xW7bm58zDW9zDf5ApAjq2LYbjt1pRk',
    appId: '1:324367349082:ios:0da3c2de4a1d77c526ef63',
    messagingSenderId: '324367349082',
    projectId: 'crud-c8dd3',
    storageBucket: 'crud-c8dd3.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH0xW7bm58zDW9zDf5ApAjq2LYbjt1pRk',
    appId: '1:324367349082:ios:0da3c2de4a1d77c526ef63',
    messagingSenderId: '324367349082',
    projectId: 'crud-c8dd3',
    storageBucket: 'crud-c8dd3.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsHvTWY2pGk5oWLuzvrgrpMM9gFTNLXTA',
    appId: '1:324367349082:web:e08acec7e2b5965926ef63',
    messagingSenderId: '324367349082',
    projectId: 'crud-c8dd3',
    authDomain: 'crud-c8dd3.firebaseapp.com',
    storageBucket: 'crud-c8dd3.firebasestorage.app',
    measurementId: 'G-SLMBNR7GRC',
  );
}
